# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hello.Request" do
    optional :name, :string, 1
  end
  add_message "hello.Reply" do
    optional :message, :string, 1
  end
end

module Hello
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.Request").msgclass
  Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.Reply").msgclass
end
